export {
  EXAGGERATED_THICKNESS_SCALE,
  EXPLODED_LAYER_GAP_MM,
  REAL_THICKNESS_SCALE,
  getExplodedPresentation,
  getPresentationThicknessScale,
  isPresentationThicknessExaggerated,
  setExplodedPresentation,
  setPresentationThicknessScale,
  subscribePresentationThicknessScale,
  toggleExplodedPresentation,
  togglePresentationThicknessScale,
  useExplodedPresentation,
  usePresentationThicknessScale,
} from '@/src/lib/presentation/thickness'
